CREATE TABLE IF NOT EXISTS "public"."help_request_assignments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "help_request_id" bigint NOT NULL,
    "phone_number" text NOT NULL,
    "people_count" integer DEFAULT 1,
    "assigned_at" timestamp with time zone DEFAULT timezone('utc', now()),
    "user_id" uuid REFERENCES auth.users(id),
    CONSTRAINT "fk_help_request" FOREIGN KEY ("help_request_id") REFERENCES "public"."help_requests"("id") ON DELETE CASCADE
);

-- Índice para acelerar las consultas basadas en help_request_id
CREATE INDEX "idx_help_request_assignments_help_request"
ON "public"."help_request_assignments" USING btree ("help_request_id");

-- Índice para acelerar las consultas basadas en user_id
CREATE INDEX "idx_help_request_assignments_user_id"
ON "public"."help_request_assignments" USING btree ("user_id");

COMMENT ON TABLE "public"."help_request_assignments" IS 'Tabla de asignación de personas a solicitudes de ayuda';
COMMENT ON COLUMN "public"."help_request_assignments"."help_request_id" IS 'ID de la solicitud de ayuda a la que se asigna esta persona';
COMMENT ON COLUMN "public"."help_request_assignments"."phone_number" IS 'Número de teléfono de la persona asignada';
COMMENT ON COLUMN "public"."help_request_assignments"."people_count" IS 'Cantidad de personas asignadas';
COMMENT ON COLUMN "public"."help_request_assignments"."user_id" IS 'ID del usuario que creó el registro';

-- Permitir SELECT para el rol anon
GRANT SELECT ON TABLE public.help_request_assignments TO anon;

-- Permitir SELECT, INSERT, UPDATE y DELETE para el rol authenticated
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.help_request_assignments TO authenticated;

ALTER TABLE public.help_request_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_can_update_own_records"
ON public.help_request_assignments
FOR UPDATE
USING (user_id = auth.uid());

CREATE POLICY "authenticated_can_delete_own_records"
ON public.help_request_assignments
FOR DELETE
USING (user_id = auth.uid());
